// <auto-generated />
using System;
using ControlFichajesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlFichajesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124161436_AddJustificanteMedicoToIncidencias")]
    partial class AddJustificanteMedicoToIncidencias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlFichajesAPI.Models.Fichaje", b =>
                {
                    b.Property<int>("Id_Fichaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fichaje");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Fichaje"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan?>("Hora_Entrada")
                        .HasColumnType("interval")
                        .HasColumnName("hora_entrada");

                    b.Property<TimeSpan?>("Hora_Salida")
                        .HasColumnType("interval")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int?>("Tiempo_Pausa")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_pausa");

                    b.HasKey("Id_Fichaje");

                    b.ToTable("fichajes", "public");
                });

            modelBuilder.Entity("ControlFichajesAPI.Models.Incidencia", b =>
                {
                    b.Property<int>("Id_Incidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Incidencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Incidencia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Fecha");

                    b.Property<string>("FechaFin")
                        .HasColumnType("text")
                        .HasColumnName("FechaFin");

                    b.Property<string>("FechaInicio")
                        .HasColumnType("text")
                        .HasColumnName("FechaInicio");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaRespuesta");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("JustificanteMedico")
                        .HasColumnType("text")
                        .HasColumnName("JustificanteMedico");

                    b.Property<string>("RespuestaAdmin")
                        .HasColumnType("text")
                        .HasColumnName("RespuestaAdmin");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Incidencia")
                        .HasColumnName("Tipo");

                    b.HasKey("Id_Incidencia");

                    b.ToTable("Incidencias", "public");
                });

            modelBuilder.Entity("ControlFichajesAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Apellido");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Contraseña");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Correo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Rol");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
